### ISSUE TITLE
segfault with "git duet" when no authors are set up

### ISSUE THREAD

**Issue by swalchemist** [git-duet/git-duet#116]
I'm reproducing #115 pretty reliably. If I run `git duet` with no parameters and without first setting up any particular authors, it will crash. The GIT_DUET_CO_AUTHORED_BY variable must be set to see the crash.

Reproduced on Ubuntu and Mac OS.

```
dfaught@ubuntu:~/workspace/git-duet$ git duet --version
0.9.0 ('0b2a4f31724b585aeafdba91123fd4cd0d298445')
dfaught@ubuntu:~/workspace/git-duet$ export GIT_DUET_CO_AUTHORED_BY=1
dfaught@ubuntu:~/workspace/git-duet$ ls ~/.git-authors
ls: cannot access '/home/dfaught/.git-authors': No such file or directory
dfaught@ubuntu:~/workspace$ git clone https://github.com/git-duet/git-duet.git
Cloning into 'git-duet'...
remote: Enumerating objects: 1437, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 1437 (delta 41), reused 110 (delta 39), pack-reused 1324
Receiving objects: 100% (1437/1437), 462.08 KiB | 6.42 MiB/s, done.
Resolving deltas: 100% (673/673), done.
dfaught@ubuntu:~/workspace$ cd git-duet/
dfaught@ubuntu:~/workspace/git-duet$ git duet
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55e56a]

goroutine 1 [running]:
github.com/git-duet/git-duet.(*GitConfig).setAuthor(0xc0000bdf38, 0x0, 0x0, 0x0)
	/home/runner/work/git-duet/git-duet/git_config.go:161 +0x1ca
github.com/git-duet/git-duet.(*GitConfig).SetAuthor(0xc0000bdf38, 0x0, 0x0, 0x0)
	/home/runner/work/git-duet/git-duet/git_config.go:105 +0x39
main.main()
	/home/runner/work/git-duet/git-duet/git-duet/main.go:77 +0xd10

```

If I add this to my config, I no longer reproduce the SEGV:
```
[duet "env"]
        git-author-initials = none
        git-author-name = Bogus
        git-author-email = bogus@example.com
```

This was found by a workstation setup script that attempts to initialize duet by running `git duet` followed by `git init` in each repo, but it seems we have to set up git-authors and define at least one author before this can work with the latest version of `git duet`. Found with the help of @Tallicia.

**Comment by professor** [comment]
I have a similar but different experience. I was following a confluence page with these steps, and I'm pretty sure that I did them in this order....

```
brew install git-duet/tap/git-duet

cat <<-EOF > ~/.git-authors
authors:
  <snip>
email:
  domain: <snip>
EOF 

cat <<-EOF > ~/.git-duet.sh
export GIT_DUET_GLOBAL=true
export GIT_DUET_CO_AUTHORED_BY=true
export GIT_DUET_ROTATE_AUTHOR=true 
EOF

git duet

git-duet-install-hook: Installed hook to /Users/todd.sedano/.git-template/hooks/prepare-commit-msg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100fa39c8]

goroutine 1 [running]:
github.com/git-duet/git-duet.(*GitConfig).setAuthor(0x1400007df28, 0x0, 0x0, 0x0)
	/home/runner/work/git-duet/git-duet/git_config.go:161 +0x198
github.com/git-duet/git-duet.(*GitConfig).SetAuthor(0x1400007df28, 0x0, 0x0, 0x0)
	/home/runner/work/git-duet/git-duet/git_config.go:105 +0x30
main.main()
	/home/runner/work/git-duet/git-duet/git-duet/main.go:77 +0xa58
```

After I ran `git duet ts ab` then running `git duet` worked fine.

**Comment by swalchemist** [comment]
Yes, that fits my experience. GIT_DUET_CO_AUTHORED_BY is true, and no authors are set (doesn't matter if you have the .git-authors file set up). 

Setting at least one author using git duet works around the problem.

**Comment by jszwedko** [comment]
Thanks for the reproduction case @professor and @swalchemist ! I opened https://github.com/git-duet/git-duet/pull/117 to address this.
