### ISSUE TITLE
please rebuild with golang 1.7.1 to have git-duet work on macOS Sierra

### ISSUE THREAD

**Issue by voelzmo** [git-duet/git-duet#35]
current binary doesn't work, can we get an updated one build with golang 1.7.1, please?

**Comment by jszwedko** [comment]
Thank you for the report! I've published a new release built with 1.7.1 (https://github.com/git-duet/git-duet/releases/tag/0.3.1). Can you try that and let me know if it works? I don't have access to a machine running Sierra.

Out of curiosity, what was the error you were seeing?

**Comment by voelzmo** [comment]
@jszwedko wow, thanks for the fast response. 0.3.1 seems to fix it. It's an error you get sporadically when e.g. doing `git duet <initial1> <initial2>`, here is an example stacktrace

```
$ git duet fr bv
failed MSpanList_Insert 0x32c2b0 0x108bd62cdf2cc 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x2e4c50, 0x32c2b0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x2e4be0, 0x1, 0x10000000003, 0xdd89)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x2eb878, 0xc208031a08)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x327000, 0x3, 0x808012000)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/asm_amd64.s:198 fp=0xc208031590 sp=0xc208031588
runtime.mallocgc(0x20, 0x15d2c0, 0x1, 0xc20801ffe0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/malloc.go:178 +0x849 fp=0xc208031640 sp=0xc208031590
runtime.newarray(0x15d2c0, 0x18, 0xc20801ffe0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/malloc.go:365 +0xc1 fp=0xc208031678 sp=0xc208031640
runtime.makeslice(0x154bc0, 0x18, 0x18, 0x0, 0x0, 0x0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/slice.go:32 +0x15c fp=0xc2080316c0 sp=0xc208031678
syscall.ByteSliceFromString(0x7fff5fbfff17, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/syscall/syscall.go:51 +0x130 fp=0xc208031740 sp=0xc2080316c0
syscall.BytePtrFromString(0x7fff5fbfff17, 0x17, 0xc20801ffe0, 0x0, 0x0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/syscall/syscall.go:65 +0x44 fp=0xc208031780 sp=0xc208031740
syscall.SlicePtrFromStrings(0xc20800d800, 0x3b, 0x3b, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/syscall/exec_unix.go:85 +0xe8 fp=0xc2080317e8 sp=0xc208031780
syscall.forkExec(0xc208035600, 0x31, 0xc208036be0, 0x5, 0x5, 0xc208031a70, 0x15d340, 0x0, 0x0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/syscall/exec_unix.go:156 +0x1d1 fp=0xc208031918 sp=0xc2080317e8
syscall.StartProcess(0xc208035600, 0x31, 0xc208036be0, 0x5, 0x5, 0xc208031a70, 0x2, 0x4, 0x0, 0x0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/syscall/exec_unix.go:238 +0x72 fp=0xc208031968 sp=0xc208031918
os.startProcess(0xc208035600, 0x31, 0xc208036be0, 0x5, 0x5, 0xc208036c80, 0x1b75c0, 0x0, 0x0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/os/exec_posix.go:45 +0x47b fp=0xc208031ac0 sp=0xc208031968
os.StartProcess(0xc208035600, 0x31, 0xc208036be0, 0x5, 0x5, 0xc208036c80, 0x2, 0x0, 0x0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/os/doc.go:24 +0x72 fp=0xc208031b10 sp=0xc208031ac0
os/exec.(*Cmd).Start(0xc20803a780, 0x0, 0x0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/os/exec/exec.go:316 +0x92e fp=0xc208031cd0 sp=0xc208031b10
os/exec.(*Cmd).Run(0xc20803a780, 0x0, 0x0)
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/os/exec/exec.go:243 +0x3a fp=0xc208031d00 sp=0xc208031cd0
git-duet.(*GitConfig).setKey(0xc20801e140, 0x201cd0, 0x12, 0xc208032650, 0xb, 0x0, 0x0)
    /home/travis/gopath/src/github.com/git-duet/git-duet/src/git-duet/git_config.go:242 +0x24f fp=0xc208031de0 sp=0xc208031d00
git-duet.(*GitConfig).setCommitter(0xc20801e140, 0xc208035280, 0x0, 0x0)
    /home/travis/gopath/src/github.com/git-duet/git-duet/src/git-duet/git_config.go:134 +0xca fp=0xc208031e20 sp=0xc208031de0
git-duet.(*GitConfig).SetCommitter(0xc20801e140, 0xc208035280, 0x0, 0x0)
    /home/travis/gopath/src/github.com/git-duet/git-duet/src/git-duet/git_config.go:86 +0x44 fp=0xc208031e48 sp=0xc208031e20
main.main()
    /home/travis/gopath/src/github.com/git-duet/git-duet/src/git-duet/git-duet/main.go:92 +0xd8b fp=0xc208031f98 sp=0xc208031e48
runtime.main()
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/proc.go:63 +0xf3 fp=0xc208031fe0 sp=0xc208031f98
runtime.goexit()
    /home/travis/.gimme/versions/go1.4.linux.amd64/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208031fe8 sp=0xc208031fe0
```

**Comment by jszwedko** [comment]
Very interesting, this appears to be related to https://github.com/golang/go/issues/16570. Thank you for bringing it up!
